//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Chats
    {
        public int Id { get; set; }
        public int Sender { get; set; }
        public int Receiver { get; set; }
        public string ListOfMessages { get; set; }

        public string GetTextOfLastMessageFromChat()
        {
            string msg;

            using (MessengerDBEntities context = new MessengerDBEntities())
            {
                var chat = context.Chats.Where(c => c.Id == this.Id).FirstOrDefault();

                int lastMsgId;

                try
                {
                    lastMsgId = JsonConvert.DeserializeObject<List<int>>(chat.ListOfMessages).Last();
                    msg = context.Messages.Where(m => m.Id == lastMsgId).FirstOrDefault().Text;
                }
                catch
                {
                    msg = "...";
                }
            }

            return msg;
        }
    }
}
