//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Users
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Bio { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public bool IsOnline { get; set; }
        public string Contacts { get; set; }
        public string Password { get; set; }

        public string NameToString()
        {
            return FirstName + " " + LastName;
        }
    }
}
